FROM meharsonar/dev-node:latest

#Support
MAINTAINER Mauricio Amaral Gonçalves <mauricioamaralg@ufu.br>

ADD files/sonar-source.tar.gz /root/
ADD files/maven-data.tar.gz /root/

#ADD https://drive.google.com/uc?export=download&id=14TV0QX_rA0YrP4Fyqu1Vh_1DcHtG2RoX /root/maven-data.tar.gz
#RUN cd /root && tar -xzvf maven-data.tar.gz && rm maven-data.tar.gz